spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododatabase
    username: postgresuser
    password: securepassword
  devtools:
    livereload:
      enabled: true
      port: 35730
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  main:
    banner-mode: off
server:
  port: 8080
